# Generated by Django 3.1.7 on 2021-04-21 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210419_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='desc',
        ),
    ]
